server:
  compression:
    enabled: true
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false
  http2:
    enabled: true
  port: 8080
